### PR TITLE
Added Travis test configuration

### PR DESCRIPTION
**Pull request by astrofrog**
@PennyQ - I logged in to Travis and enabled this repository, and this PR adds the configuration and also makes sure the scripts render once and quit but don't start the event loop (so things don't hang on Travis). We should make sure things pass before merging this PR.

### CODE REVIEW

**Comment by astrofrog** [comment]
@PennyQ - actually I didn't manage to enable Travis for this repo, I think you have to do it. Can you log in to https://travis-ci.org/ and enable it for this repository? Put a message here once you've done that. Thanks!

**Comment by PennyQ** [comment]
@astrofrog I think it's enabled now! Thanks and let me know anything else I can do!

**Comment by astrofrog** [comment]
Thanks! The build is running now, let's see what happens :)

**Comment by astrofrog** [comment]
@PennyQ - Travis now runs without errors :)

**Pull request merged**
